version: '3.8'
services:
  web:
    build: .
    ports:
        - "8000:8000"
    environment:
        - DATABASE_URL=postgresql://user:password@db:5432/wink_db
    depends_on:
        - db
    volumes:
        - .:/app

    db:
        image: postgres:15
        environment:
            - POSTGRES_DB=wink_db
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:

  